/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutCreateWorkspaceRouteImport } from './routes/_layout/create-workspace'
import { Route as LayoutCreateAgentRouteImport } from './routes/_layout/create-agent'
import { Route as LayoutActivityRouteImport } from './routes/_layout/activity'
import { Route as LayoutHostsHostIdRouteImport } from './routes/_layout/hosts/$hostId'
import { Route as LayoutHostsHostIdIndexRouteImport } from './routes/_layout/hosts/$hostId/index'
import { Route as LayoutHostsHostIdWWorkspaceIdRouteImport } from './routes/_layout/hosts/$hostId/w/$workspaceId'
import { Route as LayoutHostsHostIdAAgentIdRouteImport } from './routes/_layout/hosts/$hostId/a/$agentId'
import { Route as LayoutHostsHostIdWWorkspaceIdIndexRouteImport } from './routes/_layout/hosts/$hostId/w/$workspaceId/index'
import { Route as LayoutHostsHostIdAAgentIdIndexRouteImport } from './routes/_layout/hosts/$hostId/a/$agentId/index'
import { Route as LayoutHostsHostIdWWorkspaceIdCChatIdRouteImport } from './routes/_layout/hosts/$hostId/w/$workspaceId/c/$chatId'
import { Route as LayoutHostsHostIdAAgentIdCChatIdRouteImport } from './routes/_layout/hosts/$hostId/a/$agentId/c/$chatId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCreateWorkspaceRoute = LayoutCreateWorkspaceRouteImport.update({
  id: '/create-workspace',
  path: '/create-workspace',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutCreateAgentRoute = LayoutCreateAgentRouteImport.update({
  id: '/create-agent',
  path: '/create-agent',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutActivityRoute = LayoutActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHostsHostIdRoute = LayoutHostsHostIdRouteImport.update({
  id: '/hosts/$hostId',
  path: '/hosts/$hostId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHostsHostIdIndexRoute = LayoutHostsHostIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutHostsHostIdRoute,
} as any)
const LayoutHostsHostIdWWorkspaceIdRoute =
  LayoutHostsHostIdWWorkspaceIdRouteImport.update({
    id: '/w/$workspaceId',
    path: '/w/$workspaceId',
    getParentRoute: () => LayoutHostsHostIdRoute,
  } as any)
const LayoutHostsHostIdAAgentIdRoute =
  LayoutHostsHostIdAAgentIdRouteImport.update({
    id: '/a/$agentId',
    path: '/a/$agentId',
    getParentRoute: () => LayoutHostsHostIdRoute,
  } as any)
const LayoutHostsHostIdWWorkspaceIdIndexRoute =
  LayoutHostsHostIdWWorkspaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutHostsHostIdWWorkspaceIdRoute,
  } as any)
const LayoutHostsHostIdAAgentIdIndexRoute =
  LayoutHostsHostIdAAgentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutHostsHostIdAAgentIdRoute,
  } as any)
const LayoutHostsHostIdWWorkspaceIdCChatIdRoute =
  LayoutHostsHostIdWWorkspaceIdCChatIdRouteImport.update({
    id: '/c/$chatId',
    path: '/c/$chatId',
    getParentRoute: () => LayoutHostsHostIdWWorkspaceIdRoute,
  } as any)
const LayoutHostsHostIdAAgentIdCChatIdRoute =
  LayoutHostsHostIdAAgentIdCChatIdRouteImport.update({
    id: '/c/$chatId',
    path: '/c/$chatId',
    getParentRoute: () => LayoutHostsHostIdAAgentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/activity': typeof LayoutActivityRoute
  '/create-agent': typeof LayoutCreateAgentRoute
  '/create-workspace': typeof LayoutCreateWorkspaceRoute
  '/hosts/$hostId': typeof LayoutHostsHostIdRouteWithChildren
  '/hosts/$hostId/': typeof LayoutHostsHostIdIndexRoute
  '/hosts/$hostId/a/$agentId': typeof LayoutHostsHostIdAAgentIdRouteWithChildren
  '/hosts/$hostId/w/$workspaceId': typeof LayoutHostsHostIdWWorkspaceIdRouteWithChildren
  '/hosts/$hostId/a/$agentId/': typeof LayoutHostsHostIdAAgentIdIndexRoute
  '/hosts/$hostId/w/$workspaceId/': typeof LayoutHostsHostIdWWorkspaceIdIndexRoute
  '/hosts/$hostId/a/$agentId/c/$chatId': typeof LayoutHostsHostIdAAgentIdCChatIdRoute
  '/hosts/$hostId/w/$workspaceId/c/$chatId': typeof LayoutHostsHostIdWWorkspaceIdCChatIdRoute
}
export interface FileRoutesByTo {
  '/activity': typeof LayoutActivityRoute
  '/create-agent': typeof LayoutCreateAgentRoute
  '/create-workspace': typeof LayoutCreateWorkspaceRoute
  '/': typeof LayoutIndexRoute
  '/hosts/$hostId': typeof LayoutHostsHostIdIndexRoute
  '/hosts/$hostId/a/$agentId': typeof LayoutHostsHostIdAAgentIdIndexRoute
  '/hosts/$hostId/w/$workspaceId': typeof LayoutHostsHostIdWWorkspaceIdIndexRoute
  '/hosts/$hostId/a/$agentId/c/$chatId': typeof LayoutHostsHostIdAAgentIdCChatIdRoute
  '/hosts/$hostId/w/$workspaceId/c/$chatId': typeof LayoutHostsHostIdWWorkspaceIdCChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/activity': typeof LayoutActivityRoute
  '/_layout/create-agent': typeof LayoutCreateAgentRoute
  '/_layout/create-workspace': typeof LayoutCreateWorkspaceRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/hosts/$hostId': typeof LayoutHostsHostIdRouteWithChildren
  '/_layout/hosts/$hostId/': typeof LayoutHostsHostIdIndexRoute
  '/_layout/hosts/$hostId/a/$agentId': typeof LayoutHostsHostIdAAgentIdRouteWithChildren
  '/_layout/hosts/$hostId/w/$workspaceId': typeof LayoutHostsHostIdWWorkspaceIdRouteWithChildren
  '/_layout/hosts/$hostId/a/$agentId/': typeof LayoutHostsHostIdAAgentIdIndexRoute
  '/_layout/hosts/$hostId/w/$workspaceId/': typeof LayoutHostsHostIdWWorkspaceIdIndexRoute
  '/_layout/hosts/$hostId/a/$agentId/c/$chatId': typeof LayoutHostsHostIdAAgentIdCChatIdRoute
  '/_layout/hosts/$hostId/w/$workspaceId/c/$chatId': typeof LayoutHostsHostIdWWorkspaceIdCChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/create-agent'
    | '/create-workspace'
    | '/hosts/$hostId'
    | '/hosts/$hostId/'
    | '/hosts/$hostId/a/$agentId'
    | '/hosts/$hostId/w/$workspaceId'
    | '/hosts/$hostId/a/$agentId/'
    | '/hosts/$hostId/w/$workspaceId/'
    | '/hosts/$hostId/a/$agentId/c/$chatId'
    | '/hosts/$hostId/w/$workspaceId/c/$chatId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/activity'
    | '/create-agent'
    | '/create-workspace'
    | '/'
    | '/hosts/$hostId'
    | '/hosts/$hostId/a/$agentId'
    | '/hosts/$hostId/w/$workspaceId'
    | '/hosts/$hostId/a/$agentId/c/$chatId'
    | '/hosts/$hostId/w/$workspaceId/c/$chatId'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/activity'
    | '/_layout/create-agent'
    | '/_layout/create-workspace'
    | '/_layout/'
    | '/_layout/hosts/$hostId'
    | '/_layout/hosts/$hostId/'
    | '/_layout/hosts/$hostId/a/$agentId'
    | '/_layout/hosts/$hostId/w/$workspaceId'
    | '/_layout/hosts/$hostId/a/$agentId/'
    | '/_layout/hosts/$hostId/w/$workspaceId/'
    | '/_layout/hosts/$hostId/a/$agentId/c/$chatId'
    | '/_layout/hosts/$hostId/w/$workspaceId/c/$chatId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/create-workspace': {
      id: '/_layout/create-workspace'
      path: '/create-workspace'
      fullPath: '/create-workspace'
      preLoaderRoute: typeof LayoutCreateWorkspaceRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/create-agent': {
      id: '/_layout/create-agent'
      path: '/create-agent'
      fullPath: '/create-agent'
      preLoaderRoute: typeof LayoutCreateAgentRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/activity': {
      id: '/_layout/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof LayoutActivityRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/hosts/$hostId': {
      id: '/_layout/hosts/$hostId'
      path: '/hosts/$hostId'
      fullPath: '/hosts/$hostId'
      preLoaderRoute: typeof LayoutHostsHostIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/hosts/$hostId/': {
      id: '/_layout/hosts/$hostId/'
      path: '/'
      fullPath: '/hosts/$hostId/'
      preLoaderRoute: typeof LayoutHostsHostIdIndexRouteImport
      parentRoute: typeof LayoutHostsHostIdRoute
    }
    '/_layout/hosts/$hostId/w/$workspaceId': {
      id: '/_layout/hosts/$hostId/w/$workspaceId'
      path: '/w/$workspaceId'
      fullPath: '/hosts/$hostId/w/$workspaceId'
      preLoaderRoute: typeof LayoutHostsHostIdWWorkspaceIdRouteImport
      parentRoute: typeof LayoutHostsHostIdRoute
    }
    '/_layout/hosts/$hostId/a/$agentId': {
      id: '/_layout/hosts/$hostId/a/$agentId'
      path: '/a/$agentId'
      fullPath: '/hosts/$hostId/a/$agentId'
      preLoaderRoute: typeof LayoutHostsHostIdAAgentIdRouteImport
      parentRoute: typeof LayoutHostsHostIdRoute
    }
    '/_layout/hosts/$hostId/w/$workspaceId/': {
      id: '/_layout/hosts/$hostId/w/$workspaceId/'
      path: '/'
      fullPath: '/hosts/$hostId/w/$workspaceId/'
      preLoaderRoute: typeof LayoutHostsHostIdWWorkspaceIdIndexRouteImport
      parentRoute: typeof LayoutHostsHostIdWWorkspaceIdRoute
    }
    '/_layout/hosts/$hostId/a/$agentId/': {
      id: '/_layout/hosts/$hostId/a/$agentId/'
      path: '/'
      fullPath: '/hosts/$hostId/a/$agentId/'
      preLoaderRoute: typeof LayoutHostsHostIdAAgentIdIndexRouteImport
      parentRoute: typeof LayoutHostsHostIdAAgentIdRoute
    }
    '/_layout/hosts/$hostId/w/$workspaceId/c/$chatId': {
      id: '/_layout/hosts/$hostId/w/$workspaceId/c/$chatId'
      path: '/c/$chatId'
      fullPath: '/hosts/$hostId/w/$workspaceId/c/$chatId'
      preLoaderRoute: typeof LayoutHostsHostIdWWorkspaceIdCChatIdRouteImport
      parentRoute: typeof LayoutHostsHostIdWWorkspaceIdRoute
    }
    '/_layout/hosts/$hostId/a/$agentId/c/$chatId': {
      id: '/_layout/hosts/$hostId/a/$agentId/c/$chatId'
      path: '/c/$chatId'
      fullPath: '/hosts/$hostId/a/$agentId/c/$chatId'
      preLoaderRoute: typeof LayoutHostsHostIdAAgentIdCChatIdRouteImport
      parentRoute: typeof LayoutHostsHostIdAAgentIdRoute
    }
  }
}

interface LayoutHostsHostIdAAgentIdRouteChildren {
  LayoutHostsHostIdAAgentIdIndexRoute: typeof LayoutHostsHostIdAAgentIdIndexRoute
  LayoutHostsHostIdAAgentIdCChatIdRoute: typeof LayoutHostsHostIdAAgentIdCChatIdRoute
}

const LayoutHostsHostIdAAgentIdRouteChildren: LayoutHostsHostIdAAgentIdRouteChildren =
  {
    LayoutHostsHostIdAAgentIdIndexRoute: LayoutHostsHostIdAAgentIdIndexRoute,
    LayoutHostsHostIdAAgentIdCChatIdRoute:
      LayoutHostsHostIdAAgentIdCChatIdRoute,
  }

const LayoutHostsHostIdAAgentIdRouteWithChildren =
  LayoutHostsHostIdAAgentIdRoute._addFileChildren(
    LayoutHostsHostIdAAgentIdRouteChildren,
  )

interface LayoutHostsHostIdWWorkspaceIdRouteChildren {
  LayoutHostsHostIdWWorkspaceIdIndexRoute: typeof LayoutHostsHostIdWWorkspaceIdIndexRoute
  LayoutHostsHostIdWWorkspaceIdCChatIdRoute: typeof LayoutHostsHostIdWWorkspaceIdCChatIdRoute
}

const LayoutHostsHostIdWWorkspaceIdRouteChildren: LayoutHostsHostIdWWorkspaceIdRouteChildren =
  {
    LayoutHostsHostIdWWorkspaceIdIndexRoute:
      LayoutHostsHostIdWWorkspaceIdIndexRoute,
    LayoutHostsHostIdWWorkspaceIdCChatIdRoute:
      LayoutHostsHostIdWWorkspaceIdCChatIdRoute,
  }

const LayoutHostsHostIdWWorkspaceIdRouteWithChildren =
  LayoutHostsHostIdWWorkspaceIdRoute._addFileChildren(
    LayoutHostsHostIdWWorkspaceIdRouteChildren,
  )

interface LayoutHostsHostIdRouteChildren {
  LayoutHostsHostIdIndexRoute: typeof LayoutHostsHostIdIndexRoute
  LayoutHostsHostIdAAgentIdRoute: typeof LayoutHostsHostIdAAgentIdRouteWithChildren
  LayoutHostsHostIdWWorkspaceIdRoute: typeof LayoutHostsHostIdWWorkspaceIdRouteWithChildren
}

const LayoutHostsHostIdRouteChildren: LayoutHostsHostIdRouteChildren = {
  LayoutHostsHostIdIndexRoute: LayoutHostsHostIdIndexRoute,
  LayoutHostsHostIdAAgentIdRoute: LayoutHostsHostIdAAgentIdRouteWithChildren,
  LayoutHostsHostIdWWorkspaceIdRoute:
    LayoutHostsHostIdWWorkspaceIdRouteWithChildren,
}

const LayoutHostsHostIdRouteWithChildren =
  LayoutHostsHostIdRoute._addFileChildren(LayoutHostsHostIdRouteChildren)

interface LayoutRouteChildren {
  LayoutActivityRoute: typeof LayoutActivityRoute
  LayoutCreateAgentRoute: typeof LayoutCreateAgentRoute
  LayoutCreateWorkspaceRoute: typeof LayoutCreateWorkspaceRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutHostsHostIdRoute: typeof LayoutHostsHostIdRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutActivityRoute: LayoutActivityRoute,
  LayoutCreateAgentRoute: LayoutCreateAgentRoute,
  LayoutCreateWorkspaceRoute: LayoutCreateWorkspaceRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutHostsHostIdRoute: LayoutHostsHostIdRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
